### ISSUE TITLE
[Bug] Incorrect door lock state

### ISSUE THREAD

**Issue by junalmeida** [JoshuaMulliken/ha-wyzeapi#266]
**Describe the bug**
I can see incorrect value being shown in the home assistant UI, even after clicking UNLOCK on the home assistant entity.

**System configuration**
System: Home Assistant OS
HA Version: 2021.9.7
WyzeApi Version: 

**home-assistant.log**
** I don't have logs yet, I will add as soon as I get them. 

![image](https://user-images.githubusercontent.com/991675/136246603-6294e864-f28e-40f7-b916-4361360bbe17.png)

![image](https://user-images.githubusercontent.com/991675/136246726-c4a12afb-2f82-4abc-b393-61390fdc257a.png)

**Comment by JoshuaMulliken** [comment]
@junalmeida can you check with the latest version? I believe we just fixed this

**Comment by junalmeida** [comment]
@yoinx I also used the "UNLOCK" action in HA and the state kept unchanged.

**Comment by yoinx** [comment]
@junalmeida that's what I expected. Looking at your log, you have 2 fields as 2 and 1, during the rewrite I expected them to be 2 and 2... Not really sure why yours aren't both toggling.

https://github.com/JoshuaMulliken/wyzeapy/blob/ca08bfa34da6b5228ef9678c51989fff12ae0a41/src/wyzeapy/services/lock_service.py#L30

That's the line that's causing the trouble. If you're comfortable editing it locally, if you make it so door == 1, is 3 bet it makes it toggle ... But I'm not 100% what that might change otherwise.

**Comment by bkuri** [comment]
I'm getting similar behaviour on my wyze lock. This used to work perfectly a version or two ago, so I'm considering just downgrading for the time being.

In my case I've added a lock/unlock toggle button. Whenever I tap on it the lock does its thing correctly, *but* the auto-lock state does not. So the lock itself auto-locks, but the button state doesn't reflect the change. I need to tap on it again for it to show the correct state. Also if someone manually unlocks it, the sensor doesn't get triggered at all.

BTW I do still have the wyze app installed and those notifications do get sent correctly, so at least I'm sure that it's not due to a hardware issue.

**Comment by JoshuaMulliken** [comment]
@bkuri it is probably because of what @yoinx stated. We will see if I can get a new beta out that implements that behavior

**Comment by LordNex** [comment]
Here how mine shows up no matter what I do or what version I try. Now understand that I am currently using the lock through ZHA and also use the Keypad that comes with it so it also gets toggled through Wyze Cloud. I’ve pretty much made some hack together with IFTTT and a few other bits to toggle the state if one changes. But I’ve never been able to get the lock in this to work. I’ve looked through the logs and I’m not seeing anything related to Wyze that’s out of place

[cid:BCB79426-5FDF-4952-8C5B-DA87189D000B-L0-001]


Benjamin T Powers

On Oct 17, 2021, at 3:15 PM, Joshua Mulliken ***@***.***> wrote:

﻿

@bkuri<https://github.com/bkuri> it is probably because of what @yoinx<https://github.com/yoinx> stated. We will see if I can get a new beta out that implements that behavior

**Comment by yoinx** [comment]
Thank you, I've submitted 2 prs. One should fix this hopefully. They other should sanitize the sensitive fields that I missed in the logs. I don't really consider the Mac, parent Mac, uuid, or key as sensitive though. The UUID and key are dynamically generated so they're basically just random data. 

I could sanitize the MACs but I'm not really sure why they'd be considered sensitive. I'm open to discussion on it though.

**Comment by yoinx** [comment]
> Still showing “Unavailable” for me. I do have it paired with ZHA but it still locks and unlocks with Wyze app. I just hate using it because it tells me to recalibrate every other day. 

I don't know what would make it show as unavailable for you. I'd have to see logs for it. But, that's just a PR posted, if you cherry picked it, you'd be able to test but it's not Incorporated into anything yet.

**Comment by bkuri** [comment]
@yoinx I can confirm that the issue came back, unfortunately…

**Comment by JoshuaMulliken** [comment]
@bkuri we are having issues updating the status of the devices from the cloud. That includes the locks so they will not have the right state until we can figure out a new way to update *all* the devices.

**Comment by LordNex** [comment]
Sorry Josh but this pisses me off. And it has nothing to do with you or what you’ve accomplished. I just don’t know if this is going to continue to be worth your or our while if all we get is kick back after kick back from Wyze regarding interfacing with their products

How do they do it with IFTTT? They seem to not have an issue letting those guys use their API and I’m sure IFTTT has a larger user base the Home Assistant. So how is IFTTT not overloading their servers with its requests but a few thousand HA users eat over 50%? Something just doesn’t sound right about that to me. I just don’t think they want us in their ecosystem unfortunately, which is sad and will cost them more money than they would make, working with us to make it work well. Somewhat ashamed I even referred them to people. I have to eat a lot of crow after I told them how it didn’t have fees and then they force fees on something they said would be free.

Sorry if I’m ranting but it’s frustrating to see you and this community work so hard for Wyze to just blow us off as “not who they are marketing too”. Face it, they do not want us as customers unless we pay for cloud services. Sad, just sad Wyze

Benjamin T Powers

On Jan 20, 2022, at 8:53 PM, Joshua Mulliken ***@***.***> wrote:

﻿

@bkuri<https://github.com/bkuri> we are having issues updating the status of the devices from the cloud. That includes the locks so they will not have the right state until we can figure out a new way to update all the devices.

**Comment by junalmeida** [comment]
It seems the issue is back, I will try to gather more logs to confirm the issue is consistent.

**Comment by junalmeida** [comment]
![Screenshot_20220531_185813.jpg](https://user-images.githubusercontent.com/991675/171302723-6fc53ee2-e702-4e9f-a111-b04bdc99fef2.jpg)

![Screenshot_20220531_185728_com.hualai.jpg](https://user-images.githubusercontent.com/991675/171302732-850360e8-3076-45eb-b322-6235c246a0e6.jpg)
