### ISSUE TITLE
[Bug] Unable to find any devices + (Switch) Slider reverts to wrong setting after turning on/off

### ISSUE THREAD

**Issue by dinan5** [JoshuaMulliken/ha-wyzeapi#85]
**Describe the bug**
1. 2020-09-22 18:06:50 ERROR (MainThread) [custom_components.wyzeapi] WyzeApi authenticated but could not find any devices.  **I have 6 entities online and controllable, but I get this message.**
2. Wyze Switches, turn on and off properly, but the slider reverts back to off, when its turned on - and vice-versa.  After the second "slide" the slider is correct and matches switch status.

**To Reproduce**
1. Go to overview
2. Click on a slider for a switch
3. Switch will turn on but slider will revert to off.

**Expected behavior**
I expect slider to match switch status.  This works properly with bulbs.

**System configuration**
System: Win10/VirtualBox/Docker
HA Version:  v0.115.2 
WyzeApi Version:  

**configuration.yaml**
# Wyze 
```yaml
wyzeapi:
  username: !secret xxxx_ID
  password: !secret xxxx_PW
  sensors: false
  lock: false
  light: true
  switch: true
```

**home-assistant.log**
```
2020-09-22 17:57:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 2
2020-09-22 17:57:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 2
2020-09-22 17:57:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 1
2020-09-22 17:57:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 1
2020-09-22 17:57:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Basement Bulb
2020-09-22 17:57:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Bulb
2020-09-22 17:57:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Foyer Lamp
2020-09-22 17:57:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Foyer Lamp
2020-09-22 17:57:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Workbench
2020-09-22 17:57:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Theresa’s Light
2020-09-22 17:58:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 2
2020-09-22 17:58:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 2
2020-09-22 17:58:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 1
2020-09-22 17:58:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 1
2020-09-22 17:58:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Basement Bulb
2020-09-22 17:58:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Bulb
2020-09-22 17:58:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Foyer Lamp
2020-09-22 17:58:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Foyer Lamp
2020-09-22 17:58:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Workbench
2020-09-22 17:58:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Theresa’s Light
2020-09-22 17:58:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 2
2020-09-22 17:58:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 2
2020-09-22 17:58:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 1
2020-09-22 17:58:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 1
2020-09-22 17:58:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Basement Bulb
2020-09-22 17:58:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Bulb
2020-09-22 17:58:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Foyer Lamp
2020-09-22 17:58:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Foyer Lamp
2020-09-22 17:58:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Workbench
2020-09-22 17:58:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Theresa’s Light
2020-09-22 17:59:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 2
2020-09-22 17:59:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 2
2020-09-22 17:59:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 1
2020-09-22 17:59:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 1
2020-09-22 17:59:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Basement Bulb
2020-09-22 17:59:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Bulb
2020-09-22 17:59:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Foyer Lamp
2020-09-22 17:59:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Foyer Lamp
2020-09-22 17:59:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Workbench
2020-09-22 17:59:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Theresa’s Light
2020-09-22 17:59:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 2
2020-09-22 17:59:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 2
2020-09-22 17:59:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 1
2020-09-22 17:59:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 1
2020-09-22 17:59:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Basement Bulb
2020-09-22 17:59:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Bulb
2020-09-22 17:59:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Foyer Lamp
2020-09-22 17:59:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Foyer Lamp
2020-09-22 17:59:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Workbench
2020-09-22 17:59:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Theresa’s Light
2020-09-22 18:00:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 2
2020-09-22 18:00:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 2
2020-09-22 18:00:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 1
2020-09-22 18:00:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 1
2020-09-22 18:00:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Basement Bulb
2020-09-22 18:00:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Bulb
2020-09-22 18:00:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Foyer Lamp
2020-09-22 18:00:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Foyer Lamp
2020-09-22 18:00:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Workbench
2020-09-22 18:00:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Theresa’s Light
2020-09-22 18:00:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 2
2020-09-22 18:00:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 2
2020-09-22 18:00:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 1
2020-09-22 18:00:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 1
2020-09-22 18:00:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Basement Bulb
2020-09-22 18:00:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Bulb
2020-09-22 18:00:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Foyer Lamp
2020-09-22 18:00:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Foyer Lamp
2020-09-22 18:00:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Workbench
2020-09-22 18:00:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Theresa’s Light
2020-09-22 18:01:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 2
2020-09-22 18:01:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 2
2020-09-22 18:01:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 1
2020-09-22 18:01:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 1
2020-09-22 18:01:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Basement Bulb
2020-09-22 18:01:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Bulb
2020-09-22 18:01:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Foyer Lamp
2020-09-22 18:01:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Foyer Lamp
2020-09-22 18:01:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Workbench
2020-09-22 18:01:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Theresa’s Light
2020-09-22 18:01:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 2
2020-09-22 18:01:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 2
2020-09-22 18:01:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 1
2020-09-22 18:01:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 1
2020-09-22 18:01:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Basement Bulb
2020-09-22 18:01:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Bulb
2020-09-22 18:01:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Foyer Lamp
2020-09-22 18:01:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Foyer Lamp
2020-09-22 18:01:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Workbench
2020-09-22 18:01:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Theresa’s Light
2020-09-22 18:01:42 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Turning on: Basement Workbench
2020-09-22 18:01:42 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Workbench
2020-09-22 18:01:46 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Turning on: Basement Workbench
2020-09-22 18:01:46 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Workbench
2020-09-22 18:01:51 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Turning off: Basement Workbench
2020-09-22 18:01:51 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Workbench
2020-09-22 18:01:53 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Turning off: Basement Workbench
2020-09-22 18:01:53 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Workbench
2020-09-22 18:01:55 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Turning on: Theresa’s Light
2020-09-22 18:01:55 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Theresa’s Light
2020-09-22 18:01:59 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Turning on: Theresa’s Light
2020-09-22 18:01:59 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Theresa’s Light
2020-09-22 18:02:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 2
2020-09-22 18:02:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 2
2020-09-22 18:02:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 1
2020-09-22 18:02:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 1
2020-09-22 18:02:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Basement Bulb
2020-09-22 18:02:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Bulb
2020-09-22 18:02:01 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Foyer Lamp
2020-09-22 18:02:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Foyer Lamp
2020-09-22 18:02:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Workbench
2020-09-22 18:02:01 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Theresa’s Light
2020-09-22 18:02:03 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Turning off: Theresa’s Light
2020-09-22 18:02:03 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Theresa’s Light
2020-09-22 18:02:06 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Turning off: Theresa’s Light
2020-09-22 18:02:06 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Theresa’s Light
2020-09-22 18:02:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 2
2020-09-22 18:02:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 2
2020-09-22 18:02:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Table Lamp 1
2020-09-22 18:02:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Table Lamp 1
2020-09-22 18:02:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Basement Bulb
2020-09-22 18:02:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Bulb
2020-09-22 18:02:31 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Foyer Lamp
2020-09-22 18:02:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Foyer Lamp
2020-09-22 18:02:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Basement Workbench
2020-09-22 18:02:31 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Theresa’s Light
```

**Comment by dinan5** [comment]
Running 5.10.1 beta code

**Comment by JoshuaMulliken** [comment]
Hmm, that is interesting. I have gotten lots of support recently and will be ordering a switch in the next few days so I can check this out.

**Comment by dinan5** [comment]
Happy to help you in any way I can. this is great work that you've done.  Thank you.

________________________________

**Comment by JoshuaMulliken** [comment]
Hey, @dinan5 I have fixed the issue with the switch. My pack came in today so it was money well spent from my supporters! If you download v0.5.11 you should see that it is now working!

**Comment by dinan5** [comment]
Almost there! The issue persists when you toggle them off, sorry!

**Comment by dinan5** [comment]
5.12 fixes it, Bravo!
